// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LogItem struct {
	TeamId    int64  `json:"teamId"`
	PickGroup string `json:"pickGroup"`
	Time      string `json:"time"`
}

type LogRequest struct {
	TeamId      int64  `json:"teamId"`
	EncryptCode string `json:"encryptCode"`
}

type LogResponse struct {
	Logs []LogItem `json:"logs"`
}

type PickRequest struct {
	EncryptCode string `json:"encryptCode"`
}

type PickResponse struct {
	TeamId int64  `json:"teamId"`
	Data   string `json:"data"`
	Time   string `json:"time"`
}
