// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"lottery/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Pick a team by encryptCode
				Method:  http.MethodPost,
				Path:    "/log",
				Handler: LogHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Pick a team by encryptCode
				Method:  http.MethodPost,
				Path:    "/",
				Handler: PickHandler(serverCtx),
			},
		},
	)
}
