// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	logFieldNames          = builder.RawFieldNames(&Log{})
	logRows                = strings.Join(logFieldNames, ",")
	logRowsExpectAutoSet   = strings.Join(stringx.Remove(logFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	logRowsWithPlaceHolder = strings.Join(stringx.Remove(logFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	logModel interface {
		Insert(ctx context.Context, data *Log) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Log, error)
		FindOneByTeamId(ctx context.Context, teamId int64) (*Log, error)
		Update(ctx context.Context, data *Log) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Log struct {
		Id        int64     `db:"id"`
		TeamId    int64     `db:"team_id"`    // 队伍id
		PickGroup string    `db:"pick_group"` // 抽取组合
		Time      time.Time `db:"time"`       // 记录时间
	}
)

func newLogModel(conn sqlx.SqlConn) *defaultLogModel {
	return &defaultLogModel{
		conn:  conn,
		table: "`log`",
	}
}

func (m *defaultLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLogModel) FindOne(ctx context.Context, id int64) (*Log, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", logRows, m.table)
	var resp Log
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogModel) FindOneByTeamId(ctx context.Context, teamId int64) (*Log, error) {
	var resp Log
	query := fmt.Sprintf("select %s from %s where `team_id` = ? limit 1", logRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, teamId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogModel) Insert(ctx context.Context, data *Log) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, logRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeamId, data.PickGroup, data.Time)
	return ret, err
}

func (m *defaultLogModel) Update(ctx context.Context, newData *Log) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, logRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TeamId, newData.PickGroup, newData.Time, newData.Id)
	return err
}

func (m *defaultLogModel) tableName() string {
	return m.table
}
