// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teamFieldNames          = builder.RawFieldNames(&Team{})
	teamRows                = strings.Join(teamFieldNames, ",")
	teamRowsExpectAutoSet   = strings.Join(stringx.Remove(teamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teamRowsWithPlaceHolder = strings.Join(stringx.Remove(teamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teamModel interface {
		Insert(ctx context.Context, data *Team) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Team, error)
		Update(ctx context.Context, data *Team) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTeamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Team struct {
		Id          int64          `db:"id"`
		EncryptCode sql.NullString `db:"encrypt_code"` // 队伍秘钥
		PickContent sql.NullString `db:"pick_content"` // 抽取结果
		IsPicked    int64          `db:"is_picked"`    // 是否抽取过
		UpdateTime  sql.NullTime   `db:"update_time"`  // 更新时间
	}
)

func newTeamModel(conn sqlx.SqlConn) *defaultTeamModel {
	return &defaultTeamModel{
		conn:  conn,
		table: "`team`",
	}
}

func (m *defaultTeamModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTeamModel) FindOne(ctx context.Context, id int64) (*Team, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teamRows, m.table)
	var resp Team
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeamModel) Insert(ctx context.Context, data *Team) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, teamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.EncryptCode, data.PickContent, data.IsPicked)
	return ret, err
}

func (m *defaultTeamModel) Update(ctx context.Context, data *Team) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.EncryptCode, data.PickContent, data.IsPicked, data.Id)
	return err
}

func (m *defaultTeamModel) tableName() string {
	return m.table
}
